export const AnalyticsEvents =
{
    APP_OPENED: 'APP_OPENED',
    SIGN_IN_WITH_SLACK_STARTED: 'SIGNIN-WITH-SLACK_STARTED',
    SIGN_IN_WITH_SLACK_SUCCESS: 'SIGNIN-WITH-SLACK_SUCCESS',
    ONBOARDING_PROFILE_DISPLAYED: 'ONBOARDING-PROFILE_DISPLAYED',
    ONBOARDING_CONTEXT_DISPLAYED: 'ONBOARDING-CONTEXT_DISPLAYED',
    ONBOARDING_CALENDAR_DISPLAYED: 'ONBOARDING-CALENDAR_DISPLAYED',
    CALENDAR_INTEGRATION_STARTED: 'CALENDAR-INTEGRATION_STARTED',
    CALENDAR_INTEGRATION_SUCCESS: 'CALENDAR-INTEGRATION_SUCCESS',
};